sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  
jobs:
  include:
    - stage: Build Docker Image
      script:
      - docker build -t test .
      - docker images
      
notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - arpitapatel0611@gmail.com
    on_success: always # default: change
    on_failure: always # default: always      
